"""Recolour the site onto the Signal palette and swap in the new mark.

The amber identity predates the product having a look. This rewrites the token
block, renames the tokens (a variable called `--amber` holding pink is exactly
the drift the rest of this exercise is trying to remove), replaces the
four-corner bracket lockups with the mark, and rebuilds the favicon.
"""
import os, re, sys, urllib.parse
import loader as LD
import marks as M

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(os.path.dirname(HERE)))
PAGES = ["web/index.html", "web/privacy.html", "web/terms.html",
         "web/c/index.html", "web/ugc/index.html"]

OLD_AMBER, OLD_GROUND = "#F0A22E", "#0E1114"


def favicon_uri():
    """A 32px favicon. Flat colour and a fat grip: at this size the split is the
    only detail that survives, so nothing subtler is worth encoding."""
    svg = (
        "<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'>"
        f"<rect width='32' height='32' rx='7' fill='{M.INK}'/>"
        "<g transform='rotate(-4 16 16)'>"
        f"<path d='M9 11h13v10H9z' fill='{M.PINK}'/>"
        f"<path d='M15.4 11H23v10h-9.2z' fill='{M.CYAN}'/>"
        f"<path d='M10 8H6v16h4M22 8h4v16h-4' fill='none' stroke='{M.CREAM}' "
        "stroke-width='3'/></g></svg>")
    return "data:image/svg+xml," + urllib.parse.quote(svg, safe="/:='<>")


# The old four-corner bracket, however it is wrapped. The pages disagree on the
# svg attributes but all carry this exact path, so it is the reliable anchor.
OLD_BRACKET = re.compile(
    r'<svg[^>]*>\s*<path d="M3 8V3h5M21 8V3h-5M3 16v5h5M21 16v5h-5"[^>]*/?>\s*</svg>',
    re.S)


# web/ugc's twelve-bar spinner and web/c's rotating arc, both of which were
# standing in for `ProgressView().progressViewStyle(.circular)`. Now that the
# app draws the brand loader in every busy state, these have to follow, or the
# one thing on the screen while the user waits belongs to no brand at all.
UGC_SPIN_SM = re.compile(r'<span class="spin" aria-hidden="true">.*?</span>', re.S)
UGC_SPIN_LG = re.compile(r'<div class="spin spin--lg" aria-hidden="true">.*?</div>', re.S)
C_SPIN = re.compile(
    r'<svg (?:width="52" height="52" viewBox="0 0 52 52"|xmlns="http://www\.w3\.org/2000/svg")'
    r'[^>]*>(?:\s*<g class="spin">|(?=\s*<g transform)).*?</svg>', re.S)

# The `.spin` rules, replaced wholesale rather than left as dead CSS.
UGC_SPIN_CSS = re.compile(
    r'/\* --- the app\'s circular activity indicator.*?@media \(prefers-reduced-motion: reduce\) '
    r'\{ \.spin i \{ animation-duration: 2\.4s; \} \}', re.S)
C_SPIN_CSS = re.compile(
    r'@media \(prefers-reduced-motion: no-preference\) \{\s*'
    r'#load \.spin \{[^}]*\}\s*@keyframes spin \{[^}]*\}\s*\}', re.S)

UGC_CSS_NEW = """/* --- the app's loader ------------------------------------------------------
   The brand loader, the same animation BrandLoader.swift runs in every busy
   state. Generated by design/logo/tools/ -- do not hand-edit the markup.

   No width or height here: the loader is cut for its size, so it carries its
   own, and forcing a square onto a 2:1 mark squashes it. */
.spin { flex: none; display: inline-flex; align-items: center; }
.spin svg { display: block; }"""

# Two rules elsewhere in the page still sized the old square spinner.
UGC_ROW_CSS = re.compile(r'\.progress__row \.spin \{ width: 16px; height: 16px; \}')
UGC_WORK_CSS = re.compile(r'\.working \.spin \{ margin: 0 auto 20px; \}')

C_CSS_NEW = """/* The loader animates itself -- it is SMIL inside the SVG, not a CSS rotation,
   so Reduce Motion is handled by the markup rather than by a media query. */"""


def loader_svg(px, turning=False):
    """`px` is the square's side when turning, and the HEIGHT when not.

    Turning wherever there is room for it. The compact form has no rotation in
    it at all -- it is not a slower turn, it is a different animation -- so
    using it in a spot that could have turned quietly loses half the loader.
    Inline beside a line of text there is no room: a square box at 17px puts the
    band under 7px, so that one stays compact on purpose.
    """
    return LD.svg(f"ffl{px}{'t' if turning else ''}", px,
                  turning=turning, bracket=M.CREAM).replace("\n", " ")


def header_mark():
    """The header lockup's mark, at the 24-unit size the pages use."""
    return (
        '<svg class="mark" viewBox="0 0 44 24" aria-hidden="true">'
        '<g transform="rotate(-4 22 12)">'
        f'<path d="M8 7h27v10H8z" fill="{M.PINK}"/>'
        f'<path d="M21 7h14v10h-16z" fill="{M.CYAN}"/>'
        f'<path d="M9 3H4v18h5M35 3h5v18h-5" fill="none" stroke="{M.CREAM}" '
        'stroke-width="3.4" stroke-linecap="butt" stroke-linejoin="miter"/>'
        '</g></svg>')


def recolour(html):
    # Tokens renamed, not just redefined: a variable called `--amber` holding
    # pink is the drift this exercise exists to remove. The pages disagree on
    # the soft/line opacities, so the alpha is carried across rather than
    # flattened to one value.
    def token(mo):
        name, alpha = mo.group(1), mo.group(3)
        if name == "":
            return f"  --signal:      {M.PINK};"
        return (f"  --signal{name}: rgba(255, 46, 126, {alpha});")
    html = re.sub(r"  --amber(-soft|-line)?: *(#[0-9A-Fa-f]{6}|rgba\([^)]*?,\s*([\d.]+)\));",
                  lambda mo: token(type("m", (), {
                      "group": lambda _s, i: {1: mo.group(1) or "",
                                              3: mo.group(3)}[i]})()),
                  html)
    if "--signal:" in html and "--cyan:" not in html:
        html = html.replace(f"  --signal:      {M.PINK};",
                            f"  --signal:      {M.PINK};\n  --cyan:        {M.CYAN};", 1)
    html = html.replace("label--amber", "label--signal")
    html = html.replace("var(--amber-soft)", "var(--signal-soft)")
    html = html.replace("var(--amber-line)", "var(--signal-line)")
    html = html.replace("var(--amber)", "var(--signal)")
    html = html.replace("--ground:     #0E1114;", f"--ground:     {M.INK};")
    html = html.replace(OLD_AMBER, M.PINK).replace(OLD_AMBER.lower(), M.PINK)
    html = html.replace(f'content="{OLD_GROUND}"', f'content="{M.INK}"')
    html = html.replace("Tokens match the app: slate ground #0E1114, film-amber accent #FF2E7E,",
                        f"Tokens match the app: ink ground {M.INK}, Signal pink {M.PINK},")
    # Prose that named the old hue.
    html = html.replace('being the "film" half of "film amber". */',
                        'inherited from the film-amber this palette replaced. */')
    html = html.replace("hand sits 7px outside the rectangle so the amber edge it",
                        "hand sits 7px outside the rectangle so the signal edge it")
    return html


def main():
    changed = []
    for rel in PAGES:
        path = os.path.join(REPO, rel)
        html = open(path).read()
        before = html
        html = recolour(html)

        # favicon
        html = re.sub(r'<link rel="icon" href="data:image/svg\+xml,[^"]*">',
                      f'<link rel="icon" href="{favicon_uri()}">', html)
        # header lockup: mark, then the name as outlines rather than as type
        html = OLD_BRACKET.sub(lambda _m: header_mark(), html)

        # The mark is wider than the square bracket it replaces, so the anchor
        # must not pin it to a square. The name beside it stays as text in the
        # page's own face — it is not artwork.
        if ".brand svg.mark" not in html and ".brand {" in html:
            html = html.replace(".brand {",
                                ".brand svg.mark { height: 20px; width: auto; }\n"
                                ".brand {", 1)

        # spinners -> the brand loader
        if rel == "web/ugc/index.html":
            html = UGC_SPIN_CSS.sub(UGC_CSS_NEW, html)
            html = UGC_ROW_CSS.sub("", html)
            html = UGC_WORK_CSS.sub(
                ".working .spin { justify-content: center; margin: 0 0 20px; "
                "display: flex; }", html)
            html = UGC_SPIN_SM.sub(
                lambda _m: f'<span class="spin" aria-hidden="true">{loader_svg(17)}</span>',
                html)
            # "Adding the effect" is a centred block in a card with room to
            # spare, so it gets the full turning form.
            html = UGC_SPIN_LG.sub(
                lambda _m: f'<div class="spin spin--lg" aria-hidden="true">'
                           f'{loader_svg(56, turning=True)}</div>', html)
        if rel == "web/c/index.html":
            html = C_SPIN_CSS.sub(C_CSS_NEW, html)
            html = C_SPIN.sub(lambda _m: loader_svg(56, turning=True), html)

        if html != before:
            open(path, "w").write(html)
            changed.append(rel)
    print("recoloured:", ", ".join(changed) or "nothing")
    leftover = []
    for rel in PAGES:
        s = open(os.path.join(REPO, rel)).read()
        n = s.count("amber") + s.count(OLD_AMBER)
        if n:
            leftover.append(f"{rel}:{n}")
    print("remaining 'amber' mentions:", ", ".join(leftover) or "none")


if __name__ == "__main__":
    main()
